# ============================================================================
# github-actions.yml — CI para Evaluación Modular
# Autor: John Gómez
# Fecha: 2025-09-25
# Descripción:
#   Workflow que instala dependencias, entrena el modelo,
#   y corre los tests básicos contra la API.
# ============================================================================

name: Evaluacion Modular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python src/train_breast_cancer.py

      - name: Run tests
        run: |
          python tests/test_predict.py --base-url http://127.0.0.1:5000 &
          sleep 5
          kill %1 || true
