# ============================================================================
# github-actions.yml — CI para Evaluación Modular
# Autor: John Gómez
# Fecha: 2025-09-25
# Descripción:
#   Workflow que instala dependencias, entrena el modelo,
#   y corre los tests básicos contra la API.
# ============================================================================

name: Evaluacion Modular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Preflight: validar que los secrets EXISTEN (sin mostrarlos)
      - name: Preflight secrets
        env:
          HAS_AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          HAS_ACR_NAME: ${{ secrets.ACR_NAME }}
          HAS_ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          HAS_ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          HAS_ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          missing=0
          for v in HAS_AZURE_CREDENTIALS HAS_ACR_NAME HAS_ACR_LOGIN_SERVER HAS_ACR_USERNAME HAS_ACR_PASSWORD; do
            if [ -z "${!v}" ]; then
              echo "❌ Falta secret: $v"
              missing=1
            fi
          done
          if [ "$missing" -eq 1 ]; then
            echo "Aborto: faltan secrets requeridos."
            exit 1
          fi
          echo "✅ Secrets presentes"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install dependencies
        run: |
          az acr login -n "${{ secrets.ACR_NAME }}"
          docker build -f docker/Dockerfile -t "${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE }}:${{ env.TAG }}" .
          docker push "${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE }}:${{ env.TAG }}"

      - name: Create/Update Container App
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          python src/train_breast_cancer.py

      - name: Run tests
        run: |
          python tests/test_predict.py --base-url http://127.0.0.1:5000 &
          sleep 5
          kill %1 || true
